package mx.mc.enums;

/**
 * @author aortiz
 */
public enum CatalogoGeneral_Enum {
    DERECHOHABIENTE(1), 
    SEGURO_POPULAR(2), 
    POBLACION_ABIERTA(3), 
    IMSS(4), 
    ISSSTE(5), 
    SEDENA(6), 
    SOLTERO(7), 
    CASADO(8), 
    DIVORCIADO(9), 
    VIUDO(10), 
    OTRO(11), 
    PRIMARIA(12), 
    SECUNDARIA(13), 
    PREPARATORIA_O_BACHILLERATO(14), 
    UNIVERSIDAD(15), 
    MAESTRIA_(16), 
    DOCTORADO(17), 
    SIN_OCUPACION_(18), 
    ASALARIADO(19), 
    JUBILADOS_Y_PENSIONADOS(20), 
    MEXICANO(21), 
    NAHUAS(22), 
    MAYAS(23), 
    CATOLICA(24), 
    CRISTIANA(25), 
    O_NEGATIVO(26), 
    O_POSITIVO(27), 
    A_NEGATIVO(28), 
    CLASE_ALTA(29), 
    CASE_MEDIA_ALTA(30), 
    CLASE_MEDIA_BAJA(31), 
    SIN_VIVIENDA(32),
    OTRA_VIVIENDA(33), 
    PADRE(34),
    MADRE(35), 
    HIJO_HIJA(36), 
    COMPANERO(37), 
    MEDICAMENTO(38), 
    MATERIAL(39),
    PROTESIS(40),
    ESTADO_CIVIL_NO_DEFINIDO(41),
    RELIGION_NO_DEFINIDA(42),
    OCUPACION_NO_DEFINIDA(43),
    ESCOLARIDAD_NO_DEFINIDA(44),
    ESCOLARIDAD_NINGUNO(45), 
    GRUPO_ETNICO_NO_DEFINIDO(46), 
    GRUPO_SANGUINEO_NO_DEFINIDO(47),
    NIVEL_SOCIOECONOMICO_NO_DEFINIDO(48),
    TIPO_VIVIENDA_NO_DEFINIDA(49),
    TIPO_PARENTESCO_VECINO(50), 
    TIPO_PARENTESCO_ABUELO_MATERNO(51), 
    TIPO_PARENTESCO_CUNADA_CUNADO(52), 
    TIPO_PARENTESCO_ABUELO_PATERNO(53), 
    TIPO_PARENTESCO_DEPENDIENTE(54), 
    TIPO_PARENTESCO_ESPOSO_ESAPOSA(55), 
    TIPO_PARENTESCO_PRIMO_PRIMAA(56), 
    TIPO_PARENTESCO_SOBRINO_SOBRINA(57), 
    TIPO_PARENTESCO_TIO_TIA(58), 
    TIPO_PARENTESCO_CUIDADOR_CUIDADORA(59), 
    TIPO_PARENTESCO_NINGUNO(60), 
    TIPO_PARENTESCO_OTROS(61), 
    TIPO_PARENTESCO_AMIGO_AMIGA(62), 
    TIPO_PARENTESCO_RESPONSABLE_LEGAL_O_TUTOR(63), 
    TIPO_PARENTESCO_FAMILIAR(64), 
    TIPO_PARENTESCO_ABUELA_PATERNA(65), 
    TIPO_PARENTESCO_ABUELA_MATERNA(66), 
    TIPO_PARENTESCO_HERMANO_HERMANA(67), 
    TIPO_PARENTESCO_REPRESENTGANTE_LEGAL(68), 
    TIPO_PACIENTE_NO_DEFINIDO(69),
    TIPO_PACIENTE_PACIENTEPARTICULAR(70),
    CADUCADA(71),
    ESTABILIDAD_VENCIDA(72),
    DESVIACION_PROTECCION(73),
    DESVIACION_PREPARACION(74),
    DESVIACION_CONSERVACION(75),
    DESECHO_SEGURO(76),
    DESECHO_NO_SEGURO(77),
    DESECHO_NOSIVO(78),
    SOLO_DESECHO(79),
    UNIDAD_MEDICA_OTRA(204),
    ;

    private final int value;

    private CatalogoGeneral_Enum(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

}
