package mx.mc.enums;

/**
 *
 * @author hramirez
 */
public enum TipoMotivo_Enum {

    ENT_REABA_POR_SURTIMIENTO_DE_REABASTO(1, 1),
    DEV_REABA_MEDICAMENTO_INCORRECTO(2, 2),
    DEV_REABA_MEDICAMENTO_DANIADO(3, 2),
    DEV_REABA_MEDICAMENTO_CADUCADO(4, 2),
    AJUSTE_POR_CONTINGENCIA(5, 3),
    DEV_PRESC_ALTA_MEDICA(6, 4),
    DEV_PRESC_CAMBIO_DE_TRATAMIENTO(7, 4),
    DEV_PRESC_POR_MERMA_EN_MINISTRACION(8, 4),
    DEV_PRESC_DOSIS_INCORRECTA(9, 4),
    DEV_PRESC_RECETA_DUPLICADA(10, 4),
    DEV_PRESC_VIA_DE_ADMINISTRACION_INCORRECTA(11, 4),
    DEV_PRESC_MEDICAMENTO_CADUCADO(12, 4),
    DEV_PRESC_MEDICAMENTO_DANIADO(13, 4),
    DEV_PRESC_DEFUNCION(14, 4),
    SAL_REABAST_POR_SURTIMIENTO_DE_REABASTO(15, 5),
    SAL_DEV_MEDICAMENTO_CADUCADO(16, 6),
    SAL_DEV_MEDICAMENTO_DANIADO(17, 6),
    SAL_AJU_POR_CONTINGENCIA(18, 7),
    SAL_AJU_POR_MERMA(19, 7),
    SAL_PRESC_POR_SURTIMIENTO_DE_PRESCRIPCION(20, 8),
    DEV_CANCEL_RECETA(36,4),
    TRANS_TRANSFERENCIA_ENTRE_ALMACENES(21, 9),
    DEV_GAB_DEVOLUCION_DESDE_GABINETE(22, 4),
    ENT_CAN_SURT_CANCELACION_EN_SURTIMIENTO(23, 12),
    SAL_MINIS_POR_SURTIMIENTO_DE_PRESCRIPCION(24, 13),
    ENT_AJUSTEINVENTARIO(25,3),
    SAL_AJUSTE_INVENTARIO(26,7),
    SAL_DISPENSACION_SIN_PRESCRIPCION(27,8),
    ENT_ENTRADA_POR_TRASPASO(28,3),
    SAL_SALIDA_POR_TRASPASO(29,7),
    SAL_SALIDA_POR_DONACION(30,7),
    SAL_MERMA_POR_ACONDICIONAMIENTO_DE_UNIDOSIS(31,7),
    SAL_CADUCIDAD_VENCIDA(32,7),
    SAL_SALIDA_POR_RECETA_FARMACIA(33,8),
    SAL_SALIDA_POR_RECETA_COLECTIVA(34,8),
    DEV_CANCELACION_DE_RECETA(35,12),
    DEV_DEVOLUCION_POR_CANCELACION_DE_RECETA(36,4),
    DEV_ENTRADA_MEDICAMENTO_EXCEDENTE(37,2),
    DEV_SALIDA_MEDICAMENTO_EXCEDENTE(38,6),
    MODIFICACION_LOTE(39,7),
    MODIFICACION_CADUCIDAD(40,17),
    DISPENSACION_MANUAL(41,13),
    MEDICAMENTO_INCORRECTO(42,6),
    DISPENSACION_DE_MATERIAL(43,16),
    MODIFICACION_CANTIDAD_ACTUAL(44,7),
    MODIFICACION_CADUCIDAD_SALI(45,18),
    ;
    
    private final Integer motivoValue;
    private final Integer movimientoValue;

    private TipoMotivo_Enum(Integer motivoValue, Integer movimientoValue) {
        this.motivoValue = motivoValue;
        this.movimientoValue = movimientoValue;
    }

    public Integer getMotivoValue() {
        return motivoValue;
    }

    public Integer getMovimientoValue() {
        return movimientoValue;
    }

}
