package mx.com.dimesa.ws.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-03-01T11:38:42.375-06:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IRecetaSAFWSService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, mx.com.dimesa.ws.client.arrays.ObjectFactory.class, mx.com.dimesa.ws.client.model.ObjectFactory.class})
public interface IRecetaSAFWSService {

    @WebMethod(operationName = "Entrega", action = "http://tempuri.org/IRecetaSAFWSService/Entrega")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/Entrega", output = "http://tempuri.org/IRecetaSAFWSService/EntregaResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceEntregaRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/EntregaRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "Entrega", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Entrega")
    @ResponseWrapper(localName = "EntregaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EntregaResponse")
    @WebResult(name = "EntregaResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.ArrayOfTMAT entrega(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "codigo", targetNamespace = "http://tempuri.org/")
        java.lang.String codigo
    ) throws IRecetaSAFWSServiceEntregaRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CancelReceta", action = "http://tempuri.org/IRecetaSAFWSService/CancelReceta")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CancelReceta", output = "http://tempuri.org/IRecetaSAFWSService/CancelRecetaResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCancelRecetaRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CancelRecetaRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CancelReceta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelReceta")
    @ResponseWrapper(localName = "CancelRecetaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelRecetaResponse")
    @WebResult(name = "CancelRecetaResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado cancelReceta(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCancelRecetaRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetReceta", action = "http://tempuri.org/IRecetaSAFWSService/GetReceta")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/GetReceta", output = "http://tempuri.org/IRecetaSAFWSService/GetRecetaResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceGetRecetaRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/GetRecetaRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "GetReceta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReceta")
    @ResponseWrapper(localName = "GetRecetaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecetaResponse")
    @WebResult(name = "GetRecetaResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.ArrayOfReceta getReceta(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "recetas", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.ArrayOfReceta recetas
    ) throws IRecetaSAFWSServiceGetRecetaRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateColectivoIssemym", action = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoIssemym")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoIssemym", output = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoIssemymResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoIssemymRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CreateColectivoIssemym", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateColectivoIssemym")
    @ResponseWrapper(localName = "CreateColectivoIssemymResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateColectivoIssemymResponse")
    @WebResult(name = "CreateColectivoIssemymResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createColectivoIssemym(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateColectivo", action = "http://tempuri.org/IRecetaSAFWSService/CreateColectivo")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CreateColectivo", output = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCreateColectivoRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CreateColectivoRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CreateColectivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateColectivo")
    @ResponseWrapper(localName = "CreateColectivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateColectivoResponse")
    @WebResult(name = "CreateColectivoResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createColectivo(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCreateColectivoRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateReceta", action = "http://tempuri.org/IRecetaSAFWSService/CreateReceta")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CreateReceta", output = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCreateRecetaRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CreateReceta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateReceta")
    @ResponseWrapper(localName = "CreateRecetaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateRecetaResponse")
    @WebResult(name = "CreateRecetaResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createReceta(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCreateRecetaRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "Inventario", action = "http://tempuri.org/IRecetaSAFWSService/Inventario")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/Inventario", output = "http://tempuri.org/IRecetaSAFWSService/InventarioResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceInventarioRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/InventarioRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "Inventario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Inventario")
    @ResponseWrapper(localName = "InventarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InventarioResponse")
    @WebResult(name = "InventarioResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Long inventario(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "ClaveSAP", targetNamespace = "http://tempuri.org/")
        java.lang.String claveSAP
    ) throws IRecetaSAFWSServiceInventarioRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateRecetaMaestra", action = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaMaestra")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaMaestra", output = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaMaestraResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCreateRecetaMaestraRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaMaestraRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CreateRecetaMaestra", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateRecetaMaestra")
    @ResponseWrapper(localName = "CreateRecetaMaestraResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateRecetaMaestraResponse")
    @WebResult(name = "CreateRecetaMaestraResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createRecetaMaestra(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCreateRecetaMaestraRecetaSAFWSExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateRecetaIssemym", action = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaIssemym")
    @Action(input = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaIssemym", output = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaIssemymResponse", fault = {@FaultAction(className = IRecetaSAFWSServiceCreateRecetaIssemymRecetaSAFWSExceptionFaultFaultMessage.class, value = "http://tempuri.org/IRecetaSAFWSService/CreateRecetaIssemymRecetaSAFWSExceptionFault")})
    @RequestWrapper(localName = "CreateRecetaIssemym", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateRecetaIssemym")
    @ResponseWrapper(localName = "CreateRecetaIssemymResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateRecetaIssemymResponse")
    @WebResult(name = "CreateRecetaIssemymResult", targetNamespace = "http://tempuri.org/")
    public mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createRecetaIssemym(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Usuario usuario,
        @WebParam(name = "receta", targetNamespace = "http://tempuri.org/")
        mx.com.dimesa.ws.client.model.Receta receta
    ) throws IRecetaSAFWSServiceCreateRecetaIssemymRecetaSAFWSExceptionFaultFaultMessage;
}
