
package mx.com.dimesa.ws.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-03-01T11:38:42.340-06:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "RecetaSAFWSException", targetNamespace = "http://schemas.datacontract.org/2004/07/RecetaSAFWSAppCore.Exception")
public class IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage extends Exception {

    private static final long serialVersionUID = 1L;
    
    private mx.com.dimesa.ws.client.model.RecetaSAFWSException recetaSAFWSException;

    public IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage() {
        super();
    }
    
    public IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage(String message, mx.com.dimesa.ws.client.model.RecetaSAFWSException recetaSAFWSException) {
        super(message);
        this.recetaSAFWSException = recetaSAFWSException;
    }

    public IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage(String message, mx.com.dimesa.ws.client.model.RecetaSAFWSException recetaSAFWSException, Throwable cause) {
        super(message, cause);
        this.recetaSAFWSException = recetaSAFWSException;
    }

    public mx.com.dimesa.ws.client.model.RecetaSAFWSException getFaultInfo() {
        return this.recetaSAFWSException;
    }
}
