
package mx.com.dimesa.ws.client.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-03-01T11:38:42.258-06:00
 * Generated source version: 2.5.2
 * 
 */
public final class IRecetaSAFWSService_BasicHttpBindingIRecetaSAFWSService_Client {
    private static final Logger LOGGER = LoggerFactory.getLogger(IRecetaSAFWSService_BasicHttpBindingIRecetaSAFWSService_Client.class.getName());
    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "RecetaSAFWSService");

    private IRecetaSAFWSService_BasicHttpBindingIRecetaSAFWSService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecetaSAFWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException ex) {
                LOGGER.error(ex.getMessage());
            }
        }
      
        RecetaSAFWSService ss = new RecetaSAFWSService(wsdlURL, SERVICE_NAME);
        IRecetaSAFWSService port = ss.getBasicHttpBindingIRecetaSAFWSService();  
        
        {
        LOGGER.trace("Executing operation createRecetaMaestra");
        LOGGER.trace("Invoking entrega...");
        mx.com.dimesa.ws.client.model.Usuario entregaUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> entregaUsuarioContrasenia = null;
        entregaUsuario.setContrasenia(entregaUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> entregaUsuarioFarmacia = null;
        entregaUsuario.setFarmacia(entregaUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> entregaUsuarioNombre = null;
        entregaUsuario.setNombre(entregaUsuarioNombre);
        java.lang.String entregaCodigo = "_entrega_codigo895748493";
        try {
            mx.com.dimesa.ws.client.model.ArrayOfTMAT entregaReturn = port.entrega(entregaUsuario, entregaCodigo);
            LOGGER.trace("entrega.result={0}" , entregaReturn);
        } catch (IRecetaSAFWSServiceEntregaRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_Entrega_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking cancelReceta...");
        mx.com.dimesa.ws.client.model.Usuario cancelRecetaUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaUsuarioContrasenia = null;
        cancelRecetaUsuario.setContrasenia(cancelRecetaUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaUsuarioFarmacia = null;
        cancelRecetaUsuario.setFarmacia(cancelRecetaUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaUsuarioNombre = null;
        cancelRecetaUsuario.setNombre(cancelRecetaUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta cancelRecetaReceta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaCama = null;
        cancelRecetaReceta.setCama(cancelRecetaRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaDescripcionServicio = null;
        cancelRecetaReceta.setDescripcionServicio(cancelRecetaRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaEstatus = null;
        cancelRecetaReceta.setEstatus(cancelRecetaRecetaEstatus);
        cancelRecetaReceta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.306-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> cancelRecetaRecetaFechaReferencia = null;
        cancelRecetaReceta.setFechaReferencia(cancelRecetaRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaFolio = null;
        cancelRecetaReceta.setFolio(cancelRecetaRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaFolioPago = null;
        cancelRecetaReceta.setFolioPago(cancelRecetaRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> cancelRecetaRecetaMateriales = null;
        cancelRecetaReceta.setMateriales(cancelRecetaRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> cancelRecetaRecetaMedico = null;
        cancelRecetaReceta.setMedico(cancelRecetaRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> cancelRecetaRecetaPaciente = null;
        cancelRecetaReceta.setPaciente(cancelRecetaRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaPiso = null;
        cancelRecetaReceta.setPiso(cancelRecetaRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaServicio = null;
        cancelRecetaReceta.setServicio(cancelRecetaRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> cancelRecetaRecetaTipo = null;
        cancelRecetaReceta.setTipo(cancelRecetaRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado cancelRecetaReturn = port.cancelReceta(cancelRecetaUsuario, cancelRecetaReceta);
            LOGGER.trace("cancelReceta.result={0}" , cancelRecetaReturn);

        } catch (IRecetaSAFWSServiceCancelRecetaRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CancelReceta_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking getReceta...");
        mx.com.dimesa.ws.client.model.Usuario getRecetaUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaUsuarioContrasenia = null;
        getRecetaUsuario.setContrasenia(getRecetaUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaUsuarioFarmacia = null;
        getRecetaUsuario.setFarmacia(getRecetaUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaUsuarioNombre = null;
        getRecetaUsuario.setNombre(getRecetaUsuarioNombre);
        mx.com.dimesa.ws.client.model.ArrayOfReceta getRecetaRecetas = new mx.com.dimesa.ws.client.model.ArrayOfReceta();
        java.util.List<mx.com.dimesa.ws.client.model.Receta> getRecetaRecetasReceta = new java.util.ArrayList<>();
        mx.com.dimesa.ws.client.model.Receta getRecetaRecetasRecetaVal1 = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Cama = null;
        getRecetaRecetasRecetaVal1.setCama(getRecetaRecetasRecetaVal1Cama);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1DescripcionServicio = null;
        getRecetaRecetasRecetaVal1.setDescripcionServicio(getRecetaRecetasRecetaVal1DescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Estatus = null;
        getRecetaRecetasRecetaVal1.setEstatus(getRecetaRecetasRecetaVal1Estatus);
        getRecetaRecetasRecetaVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.309-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> getRecetaRecetasRecetaVal1FechaReferencia = null;
        getRecetaRecetasRecetaVal1.setFechaReferencia(getRecetaRecetasRecetaVal1FechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Folio = null;
        getRecetaRecetasRecetaVal1.setFolio(getRecetaRecetasRecetaVal1Folio);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1FolioPago = null;
        getRecetaRecetasRecetaVal1.setFolioPago(getRecetaRecetasRecetaVal1FolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> getRecetaRecetasRecetaVal1Materiales = null;
        getRecetaRecetasRecetaVal1.setMateriales(getRecetaRecetasRecetaVal1Materiales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> getRecetaRecetasRecetaVal1Medico = null;
        getRecetaRecetasRecetaVal1.setMedico(getRecetaRecetasRecetaVal1Medico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> getRecetaRecetasRecetaVal1Paciente = null;
        getRecetaRecetasRecetaVal1.setPaciente(getRecetaRecetasRecetaVal1Paciente);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Piso = null;
        getRecetaRecetasRecetaVal1.setPiso(getRecetaRecetasRecetaVal1Piso);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Servicio = null;
        getRecetaRecetasRecetaVal1.setServicio(getRecetaRecetasRecetaVal1Servicio);
        javax.xml.bind.JAXBElement<java.lang.String> getRecetaRecetasRecetaVal1Tipo = null;
        getRecetaRecetasRecetaVal1.setTipo(getRecetaRecetasRecetaVal1Tipo);
        getRecetaRecetasReceta.add(getRecetaRecetasRecetaVal1);
        getRecetaRecetas.getReceta().addAll(getRecetaRecetasReceta);
        try {
            mx.com.dimesa.ws.client.model.ArrayOfReceta getRecetaReturn = port.getReceta(getRecetaUsuario, getRecetaRecetas);
            LOGGER.trace("getReceta.result={0}" , getRecetaReturn);

        } catch (IRecetaSAFWSServiceGetRecetaRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_GetReceta_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking createColectivoIssemym...");
        mx.com.dimesa.ws.client.model.Usuario createColectivoIssemymUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymUsuarioContrasenia = null;
        createColectivoIssemymUsuario.setContrasenia(createColectivoIssemymUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymUsuarioFarmacia = null;
        createColectivoIssemymUsuario.setFarmacia(createColectivoIssemymUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymUsuarioNombre = null;
        createColectivoIssemymUsuario.setNombre(createColectivoIssemymUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta createColectivoIssemymReceta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaCama = null;
        createColectivoIssemymReceta.setCama(createColectivoIssemymRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaDescripcionServicio = null;
        createColectivoIssemymReceta.setDescripcionServicio(createColectivoIssemymRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaEstatus = null;
        createColectivoIssemymReceta.setEstatus(createColectivoIssemymRecetaEstatus);
        createColectivoIssemymReceta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.311-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> createColectivoIssemymRecetaFechaReferencia = null;
        createColectivoIssemymReceta.setFechaReferencia(createColectivoIssemymRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaFolio = null;
        createColectivoIssemymReceta.setFolio(createColectivoIssemymRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaFolioPago = null;
        createColectivoIssemymReceta.setFolioPago(createColectivoIssemymRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> createColectivoIssemymRecetaMateriales = null;
        createColectivoIssemymReceta.setMateriales(createColectivoIssemymRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> createColectivoIssemymRecetaMedico = null;
        createColectivoIssemymReceta.setMedico(createColectivoIssemymRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> createColectivoIssemymRecetaPaciente = null;
        createColectivoIssemymReceta.setPaciente(createColectivoIssemymRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaPiso = null;
        createColectivoIssemymReceta.setPiso(createColectivoIssemymRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaServicio = null;
        createColectivoIssemymReceta.setServicio(createColectivoIssemymRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoIssemymRecetaTipo = null;
        createColectivoIssemymReceta.setTipo(createColectivoIssemymRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createColectivoIssemymReturn = port.createColectivoIssemym(createColectivoIssemymUsuario, createColectivoIssemymReceta);
            LOGGER.trace("createColectivoIssemym.result={0}" , createColectivoIssemymReturn);

        } catch (IRecetaSAFWSServiceCreateColectivoIssemymRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CreateColectivoIssemym_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking createColectivo...");
        mx.com.dimesa.ws.client.model.Usuario createColectivoUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoUsuarioContrasenia = null;
        createColectivoUsuario.setContrasenia(createColectivoUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoUsuarioFarmacia = null;
        createColectivoUsuario.setFarmacia(createColectivoUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoUsuarioNombre = null;
        createColectivoUsuario.setNombre(createColectivoUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta createColectivoReceta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaCama = null;
        createColectivoReceta.setCama(createColectivoRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaDescripcionServicio = null;
        createColectivoReceta.setDescripcionServicio(createColectivoRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaEstatus = null;
        createColectivoReceta.setEstatus(createColectivoRecetaEstatus);
        createColectivoReceta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.313-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> createColectivoRecetaFechaReferencia = null;
        createColectivoReceta.setFechaReferencia(createColectivoRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaFolio = null;
        createColectivoReceta.setFolio(createColectivoRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaFolioPago = null;
        createColectivoReceta.setFolioPago(createColectivoRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> createColectivoRecetaMateriales = null;
        createColectivoReceta.setMateriales(createColectivoRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> createColectivoRecetaMedico = null;
        createColectivoReceta.setMedico(createColectivoRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> createColectivoRecetaPaciente = null;
        createColectivoReceta.setPaciente(createColectivoRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaPiso = null;
        createColectivoReceta.setPiso(createColectivoRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaServicio = null;
        createColectivoReceta.setServicio(createColectivoRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createColectivoRecetaTipo = null;
        createColectivoReceta.setTipo(createColectivoRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createColectivoReturn = port.createColectivo(createColectivoUsuario, createColectivoReceta);
            LOGGER.trace("createColectivo.result={0}" , createColectivoReturn);

        } catch (IRecetaSAFWSServiceCreateColectivoRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CreateColectivo_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking createReceta...");
        mx.com.dimesa.ws.client.model.Usuario createRecetaUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaUsuarioContrasenia = null;
        createRecetaUsuario.setContrasenia(createRecetaUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaUsuarioFarmacia = null;
        createRecetaUsuario.setFarmacia(createRecetaUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaUsuarioNombre = null;
        createRecetaUsuario.setNombre(createRecetaUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta createRecetaReceta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaCama = null;
        createRecetaReceta.setCama(createRecetaRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaDescripcionServicio = null;
        createRecetaReceta.setDescripcionServicio(createRecetaRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaEstatus = null;
        createRecetaReceta.setEstatus(createRecetaRecetaEstatus);
        createRecetaReceta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.315-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> createRecetaRecetaFechaReferencia = null;
        createRecetaReceta.setFechaReferencia(createRecetaRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaFolio = null;
        createRecetaReceta.setFolio(createRecetaRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaFolioPago = null;
        createRecetaReceta.setFolioPago(createRecetaRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> createRecetaRecetaMateriales = null;
        createRecetaReceta.setMateriales(createRecetaRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> createRecetaRecetaMedico = null;
        createRecetaReceta.setMedico(createRecetaRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> createRecetaRecetaPaciente = null;
        createRecetaReceta.setPaciente(createRecetaRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaPiso = null;
        createRecetaReceta.setPiso(createRecetaRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaServicio = null;
        createRecetaReceta.setServicio(createRecetaRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaRecetaTipo = null;
        createRecetaReceta.setTipo(createRecetaRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createRecetaReturn = port.createReceta(createRecetaUsuario, createRecetaReceta);
            LOGGER.trace("createReceta.result={0}" , createRecetaReturn);

        } catch (IRecetaSAFWSServiceCreateRecetaRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CreateReceta_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking inventario...");
        mx.com.dimesa.ws.client.model.Usuario inventarioUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> inventarioUsuarioContrasenia = null;
        inventarioUsuario.setContrasenia(inventarioUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> inventarioUsuarioFarmacia = null;
        inventarioUsuario.setFarmacia(inventarioUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> inventarioUsuarioNombre = null;
        inventarioUsuario.setNombre(inventarioUsuarioNombre);
        java.lang.String inventarioClaveSAP = "_inventario_claveSAP1916207609";
        try {
            java.lang.Long inventarioReturn = port.inventario(inventarioUsuario, inventarioClaveSAP);
            LOGGER.trace("inventario.result={}" , inventarioReturn);

        } catch (IRecetaSAFWSServiceInventarioRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_Inventario_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking createRecetaMaestra...");
        mx.com.dimesa.ws.client.model.Usuario createRecetaMaestraUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraUsuarioContrasenia = null;
        createRecetaMaestraUsuario.setContrasenia(createRecetaMaestraUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraUsuarioFarmacia = null;
        createRecetaMaestraUsuario.setFarmacia(createRecetaMaestraUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraUsuarioNombre = null;
        createRecetaMaestraUsuario.setNombre(createRecetaMaestraUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta createRecetaMaestraReceta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaCama = null;
        createRecetaMaestraReceta.setCama(createRecetaMaestraRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaDescripcionServicio = null;
        createRecetaMaestraReceta.setDescripcionServicio(createRecetaMaestraRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaEstatus = null;
        createRecetaMaestraReceta.setEstatus(createRecetaMaestraRecetaEstatus);
        createRecetaMaestraReceta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.318-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> createRecetaMaestraRecetaFechaReferencia = null;
        createRecetaMaestraReceta.setFechaReferencia(createRecetaMaestraRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaFolio = null;
        createRecetaMaestraReceta.setFolio(createRecetaMaestraRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaFolioPago = null;
        createRecetaMaestraReceta.setFolioPago(createRecetaMaestraRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> createRecetaMaestraRecetaMateriales = null;
        createRecetaMaestraReceta.setMateriales(createRecetaMaestraRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> createRecetaMaestraRecetaMedico = null;
        createRecetaMaestraReceta.setMedico(createRecetaMaestraRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> createRecetaMaestraRecetaPaciente = null;
        createRecetaMaestraReceta.setPaciente(createRecetaMaestraRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaPiso = null;
        createRecetaMaestraReceta.setPiso(createRecetaMaestraRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaServicio = null;
        createRecetaMaestraReceta.setServicio(createRecetaMaestraRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaMaestraRecetaTipo = null;
        createRecetaMaestraReceta.setTipo(createRecetaMaestraRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createRecetaMaestraReturn = port.createRecetaMaestra(createRecetaMaestraUsuario, createRecetaMaestraReceta);
            LOGGER.trace("createRecetaMaestra.result={0}" , createRecetaMaestraReturn);

        } catch (IRecetaSAFWSServiceCreateRecetaMaestraRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CreateRecetaMaestra_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }
        {
        LOGGER.trace("Invoking createRecetaIssemym...");
        mx.com.dimesa.ws.client.model.Usuario createRecetaIssemymUsuario = new mx.com.dimesa.ws.client.model.Usuario();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymUsuarioContrasenia = null;
        createRecetaIssemymUsuario.setContrasenia(createRecetaIssemymUsuarioContrasenia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymUsuarioFarmacia = null;
        createRecetaIssemymUsuario.setFarmacia(createRecetaIssemymUsuarioFarmacia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymUsuarioNombre = null;
        createRecetaIssemymUsuario.setNombre(createRecetaIssemymUsuarioNombre);
        mx.com.dimesa.ws.client.model.Receta _createRecetaIssemym_receta = new mx.com.dimesa.ws.client.model.Receta();
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaCama = null;
        _createRecetaIssemym_receta.setCama(createRecetaIssemymRecetaCama);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaDescripcionServicio = null;
        _createRecetaIssemym_receta.setDescripcionServicio(createRecetaIssemymRecetaDescripcionServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaEstatus = null;
        _createRecetaIssemym_receta.setEstatus(createRecetaIssemymRecetaEstatus);
        _createRecetaIssemym_receta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-01T11:38:42.320-06:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> createRecetaIssemymRecetaFechaReferencia = null;
        _createRecetaIssemym_receta.setFechaReferencia(createRecetaIssemymRecetaFechaReferencia);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaFolio = null;
        _createRecetaIssemym_receta.setFolio(createRecetaIssemymRecetaFolio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaFolioPago = null;
        _createRecetaIssemym_receta.setFolioPago(createRecetaIssemymRecetaFolioPago);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.ArrayOfRecetaMaterial> createRecetaIssemymRecetaMateriales = null;
        _createRecetaIssemym_receta.setMateriales(createRecetaIssemymRecetaMateriales);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Medico> createRecetaIssemymRecetaMedico = null;
        _createRecetaIssemym_receta.setMedico(createRecetaIssemymRecetaMedico);
        javax.xml.bind.JAXBElement<mx.com.dimesa.ws.client.model.Paciente> createRecetaIssemymRecetaPaciente = null;
        _createRecetaIssemym_receta.setPaciente(createRecetaIssemymRecetaPaciente);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaPiso = null;
        _createRecetaIssemym_receta.setPiso(createRecetaIssemymRecetaPiso);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaServicio = null;
        _createRecetaIssemym_receta.setServicio(createRecetaIssemymRecetaServicio);
        javax.xml.bind.JAXBElement<java.lang.String> createRecetaIssemymRecetaTipo = null;
        _createRecetaIssemym_receta.setTipo(createRecetaIssemymRecetaTipo);
        try {
            mx.com.dimesa.ws.client.model.RecetaSAFWSResultado createRecetaIssemymReturn = port.createRecetaIssemym(createRecetaIssemymUsuario, _createRecetaIssemym_receta);
            LOGGER.trace("createRecetaIssemym.result={0}" , createRecetaIssemymReturn);

        } catch (IRecetaSAFWSServiceCreateRecetaIssemymRecetaSAFWSExceptionFaultFaultMessage e) { 
            LOGGER.trace("Expected exception: IRecetaSAFWSService_CreateRecetaIssemym_RecetaSAFWSExceptionFault_FaultMessage has occurred.");
            LOGGER.trace(e.toString());
        }
            }

        System.exit(0);
    }

}
