package mx.com.dimesa.ws.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-03-01T11:38:42.383-06:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "RecetaSAFWSService", 
                  wsdlLocation = "http://svcsafb2b.dimesa.com.mx/RecetaSAFWSService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class RecetaSAFWSService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tempuri.org/", "RecetaSAFWSService");
    public static final QName BasicHttpBindingIRecetaSAFWSService = new QName("http://tempuri.org/", "BasicHttpBinding_IRecetaSAFWSService");
    static {
        URL url = null;
        try {
            url = new URL("http://svcsafb2b.dimesa.com.mx/RecetaSAFWSService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecetaSAFWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://svcsafb2b.dimesa.com.mx/RecetaSAFWSService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecetaSAFWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecetaSAFWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecetaSAFWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecetaSAFWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecetaSAFWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecetaSAFWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IRecetaSAFWSService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRecetaSAFWSService")
    public IRecetaSAFWSService getBasicHttpBindingIRecetaSAFWSService() {
        return super.getPort(BasicHttpBindingIRecetaSAFWSService, IRecetaSAFWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRecetaSAFWSService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRecetaSAFWSService")
    public IRecetaSAFWSService getBasicHttpBindingIRecetaSAFWSService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRecetaSAFWSService, IRecetaSAFWSService.class, features);
    }

}
