package mx.gob.imss.siap.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-09T17:11:43.873-06:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "wsCatalogoEmpleados",
                  wsdlLocation = "classpath:wsdl/wsSIAP.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class WsCatalogoEmpleados extends Service {

    public static final URL WSDL_LOCATION = null;

    public static final QName SERVICE = new QName("http://tempuri.org/", "wsCatalogoEmpleados");
    public static final QName WsCatalogoEmpleadosSoap = new QName("http://tempuri.org/", "wsCatalogoEmpleadosSoap");

    public WsCatalogoEmpleados(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsCatalogoEmpleados(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCatalogoEmpleados() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsCatalogoEmpleados(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsCatalogoEmpleados(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsCatalogoEmpleados(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsCatalogoEmpleadosSoap
     */
    @WebEndpoint(name = "wsCatalogoEmpleadosSoap")
    public WsCatalogoEmpleadosSoap getWsCatalogoEmpleadosSoap() {
        return super.getPort(WsCatalogoEmpleadosSoap, WsCatalogoEmpleadosSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCatalogoEmpleadosSoap
     */
    @WebEndpoint(name = "wsCatalogoEmpleadosSoap")
    public WsCatalogoEmpleadosSoap getWsCatalogoEmpleadosSoap(WebServiceFeature... features) {
        return super.getPort(WsCatalogoEmpleadosSoap, WsCatalogoEmpleadosSoap.class, features);
    }

}
